services:
  - type: web
    name: copa-2026-database
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: "3.11.9"